### ISSUE TITLE
Failed to load the titanium-alloy package

### ISSUE THREAD

**Issue by nicka** [yomybaby/atom-titanium#1]
**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [titanium-alloy](https://github.com/yomybaby/atom-titanium) package, v0.3.3

### Stack Trace

Failed to load the titanium-alloy package

```
At ENOENT: no such file or directory, open '/usr/local/lib/node_modules/alloy/docs/api.jsca'

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/alloy/docs/api.jsca'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.readFileSync (fs.js:396:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
    at Object.<anonymous> (/Users/nickdenengelsman/.atom/packages/titanium-alloy/lib/controllerProvider.coffee:6:23)
    at Object.<anonymous> (/Users/nickdenengelsman/.atom/packages/titanium-alloy/lib/controllerProvider.coffee:66:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/nickdenengelsman/.atom/packages/titanium-alloy/lib/main.coffee:8:16)
    at Object.<anonymous> (/Users/nickdenengelsman/.atom/packages/titanium-alloy/lib/main.coffee:21:4)
    at Module._compile (module.js:452:26)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "railscast-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
build, v0.42.0
go-to-view, v0.3.0
linter, v1.2.4
linter-reek, v2.0.0
linter-rubocop, v0.2.7
linter-ruby, v0.1.6
railscast-theme, v0.3.0
ruby-block-converter, v3.5.0
titanium-alloy, v0.3.3

# Dev
No dev packages
```

**Comment by yomybaby** [comment]
Thanks for 1st issue :smile: 
Your node module path is not `/usr/local/lib/node_modules/` or You are not install Alloy.
Run a below command on Terminal
```
$ which alloy
```

BTW, packages/titanium-alloy/lib/controllerProvider.coffee is not completed code. so I'll remove right a way.
Gve me a second.

**Comment by nicka** [comment]
No problem. Maybe it's because I use NVM? Anyways it should be possible to set the  alloy path via the package settings. Would this be an opition?

Verstuurd vanaf mijn iPhone
