### ISSUE TITLE
Autocomplete on XML

### ISSUE THREAD

**Issue by DouglasHennrich** [yomybaby/atom-titanium#15]
Autocomplete is not working as your `gif` shows...
I try to start to type `<Button` then press `tab` and nothing happens =/

the syntax are marked as `ALLOY.XML`

* package `v0.6.1`

**Comment by yomybaby** [comment]
Thanks for reporting.

This autocomplete feature is powered by [autocomplete-plus](https://github.com/atom/autocomplete-plus)
Make sure to enable autocomplete-plus package. It's a default package of atom.

If it is enabled already, please let me know more detail of your system. (version of your atom, os ... )

**Comment by DouglasHennrich** [comment]
already enabled =/

* Mac OSX 10.11.1
* Atom 1.1.0
* Autocomplete-plus 2.22.0

**Comment by DouglasHennrich** [comment]
note:
I don't have any other package for deal with XML files. Only `Emmet`, but I disable it and try again and nothing happens too =/

**Comment by yomybaby** [comment]
Is there any error on console (alt+cmd+i)?

**Comment by DouglasHennrich** [comment]
```shell
/Users/DHennrich/.atom/packages/emmet/lib/emmet.coffee:133 Loading Emmet extensions from ~/emmet
/Users/DHennrich/.atom/packages/emmet/lib/emmet.coffee:150 Emmet: no such extension folder: /Users/DHennrich/emmet
index.js:46 Window load time: 4250ms
https://www.google-analytics.com/collect?t=event&ec=window&ea=ended&ev=4069…c13256bed76a8cb52e10789455991bda7&an=atom&av=1.1.0&sr=1280x800&aiid=stable Failed to load resource: net::ERR_NAME_NOT_RESOLVED
https://www.google-analytics.com/collect?t=event&ec=window&ea=started&v=1&t…c13256bed76a8cb52e10789455991bda7&an=atom&av=1.1.0&sr=1280x800&aiid=stable Failed to load resource: net::ERR_NAME_NOT_RESOLVED
https://www.google-analytics.com/collect?t=timing&utc=shell&utv=load&utt=65…c13256bed76a8cb52e10789455991bda7&an=atom&av=1.1.0&sr=1280x800&aiid=stable Failed to load resource: net::ERR_NAME_NOT_RESOLVED
https://www.google-analytics.com/collect?t=timing&utc=core&utv=load&utt=425…c13256bed76a8cb52e10789455991bda7&an=atom&av=1.1.0&sr=1280x800&aiid=stable Failed to load resource: net::ERR_NAME_NOT_RESOLVED
https://www.google-analytics.com/collect?t=event&ec=deprecation-v3&ea=color…c13256bed76a8cb52e10789455991bda7&an=atom&av=1.1.0&sr=1280x800&aiid=stable Failed to load resource: net::ERR_NAME_NOT_RESOLVED
https://www.google-analytics.com/collect?t=event&ec=deprecation-v3&ea=color…c13256bed76a8cb52e10789455991bda7&an=atom&av=1.1.0&sr=1280x800&aiid=stable Failed to load resource: net::ERR_NAME_NOT_RESOLVED
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/main.js:129 Fetching outdated packages and themes failed. Error: Fetching outdated packages and themes failed.
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:177:21
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by DouglasHennrich** [comment]
I remove `Emmet` and other plugins and re-install `Titanium-Alloy` and now it's working :D
