### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by FokkeZB** [yomybaby/atom-titanium#23]
Hey @yomybaby, awesome plugin!

I was running into this error while editing:

```
"ItemTemplate": {
  selectionStyle: Ti.UI.iPhone.ListViewCellSelectionStyle.NONE,
  canEdit: true,
  editActions: [
    {
      title: 'All',
      style: Ti.UI.iOS.ROW_ACTION_STYLE_NORMAL
    }, {
      title: '+ Thumbnail',
      color: '#ccc'
    }, {
      title: 'Meta',
      style: Ti.UI.iOS.ROW_ACTION_STYLE_NORMAL
    }
  ]
}
```

**Atom Version**: 1.3.0
**System**: Mac OS X 10.11.2
**Thrown From**: [titanium-alloy](https://github.com/yomybaby/atom-titanium) package, v0.6.9

### Stack Trace

Uncaught TypeError: Cannot read property 'type' of undefined

```
At /Users/fokkezb/.atom/packages/titanium-alloy/lib/styleProvider.coffee:220

TypeError: Cannot read property 'type' of undefined
    at Object.module.exports.getPropertyValueCompletions (/Users/fokkezb/.atom/packages/titanium-alloy/lib/styleProvider.coffee:220:36)
    at Object.module.exports.getSuggestions (/Users/fokkezb/.atom/packages/titanium-alloy/lib/styleProvider.coffee:32:22)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:265:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:252:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -1:04.6.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -1:04.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:03.5.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -1:03.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:02.5.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -1:02.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:54.2.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:40.1.0 core:select-right (atom-text-editor.editor.is-focused)
  6x -0:37.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:36.6.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:35.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:34.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:02.7.0 core:move-left (atom-text-editor.editor.is-focused)
  5x -0:02.3.0 core:select-right (atom-text-editor.editor.is-focused)
  2x -0:00.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:00.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.19
docblockr, v0.7.3
hyperclick, v0.0.35
linter, v1.11.3
linter-jshint, v1.2.1
titanium-alloy, v0.6.9

# Dev
No dev packages
```

**Comment by yomybaby** [comment]
Thanks for detail reporting!!
I'll check it tonight or tomorrow. :)

2015년 12월 10일 (목) 오후 6:46, Fokke Zandbergen <notifications@github.com>님이 작성:

**Comment by yomybaby** [comment]
bump up v0.6.10 :smile:
