### ISSUE TITLE
Uncaught TypeError: Cannot read property 'functions' of undefined

### ISSUE THREAD

**Issue by bigcup** [yomybaby/atom-titanium#27]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.3
**System**: Mac OS X 10.10.5
**Thrown From**: [titanium-alloy](https://github.com/yomybaby/atom-titanium) package, v0.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'functions' of undefined

```
At /Users/developer/.atom/packages/titanium-alloy/lib/controllerProvider.coffee:64

TypeError: Cannot read property 'functions' of undefined
    at Object.module.exports.getSuggestions (/Users/developer/.atom/packages/titanium-alloy/lib/controllerProvider.coffee:64:30)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:290:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:269:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:256:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -1:24.6.0 core:paste (atom-text-editor.editor.is-focused)
     -1:21.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:16.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  5x -1:16.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:04.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:04.6.0 core:cancel (atom-text-editor.editor.is-focused)
  3x -1:00.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:43.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:43.4.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:40 editor:newline (atom-text-editor.editor.is-focused)
  6x -0:29.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:17 core:save (atom-text-editor.editor.is-focused)
     -0:11 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.theme-oceanic-next.theme-one-dark-ui)
     -0:08.8.0 core:undo (atom-text-editor.editor.is-focused)
     -0:05.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:05.4.0 core:cancel (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "related-split-view"
    ],
    "themes": [
      "one-dark-ui",
      "oceanic-next"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-backbone, v0.6.1
atom-beautify, v0.28.21
atom-pair, v2.0.10
atom-ternjs, v0.13.2
autocomplete-modules, v1.3.1
autocomplete-paths, v1.0.2
build, v0.54.1
emmet, v2.4.1
highlight-selected, v0.11.2
hyperclick, v0.0.35
javascript-snippets, v1.2.0
linter, v1.11.3
linter-jshint, v1.3.0
linter-jsonlint, v1.1.5
minimap, v4.19.0
oceanic-next, v0.1.2
project-manager, v2.7.6
release-notes, v0.53.0
sync-settings, v0.6.0
terminal-plus, v0.14.5
titanium-alloy, v0.8.1
titanium-build, v0.8.1

# Dev
No dev packages
```

**Comment by yomybaby** [comment]
Thanks for reporting :+1:
