### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apiName' of undefined

### ISSUE THREAD

**Issue by FokkeZB** [yomybaby/atom-titanium#28]
[Enter steps to reproduce below:]

Every now and then as I start editing I run into these errors all the time. No idea why.

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [titanium-alloy](https://github.com/yomybaby/atom-titanium) package, v0.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'apiName' of undefined

```
At /Users/fokkezb/.atom/packages/titanium-alloy/lib/controllerProvider.coffee:62

TypeError: Cannot read property 'apiName' of undefined
    at Object.module.exports.getSuggestions (/Users/fokkezb/.atom/packages/titanium-alloy/lib/controllerProvider.coffee:62:50)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:290:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:269:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:256:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
 14x -4:51.5.0 core:close (atom-text-editor.editor.is-focused)
  3x -0:16 core:undo (atom-text-editor.editor.is-focused)
     -0:14.5.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:13.6.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -0:13.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-ternjs"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.22
dash, v1.6.0
docblockr, v0.7.3
hyperclick, v0.0.35
linter, v1.11.3
linter-jshint, v1.3.1
titanium-alloy, v0.8.1

# Dev
No dev packages
```

**Comment by yomybaby** [comment]
Thanks for reporting :+1:
