### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prefix' of undefined

### ISSUE THREAD

**Issue by bigcup** [yomybaby/atom-titanium#30]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.10.5
**Thrown From**: [titanium-alloy](https://github.com/yomybaby/atom-titanium) package, v0.9.0

### Stack Trace

Uncaught TypeError: Cannot read property 'prefix' of undefined

```
At /Users/developer/.atom/packages/titanium-alloy/lib/viewProvider.coffee:118

TypeError: Cannot read property 'prefix' of undefined
    at Object.module.exports.getTagNameCompletions (/Users/developer/.atom/packages/titanium-alloy/lib/viewProvider.coffee:118:27)
    at Object.module.exports.getSuggestions (/Users/developer/.atom/packages/titanium-alloy/lib/viewProvider.coffee:39:22)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:290:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:269:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:256:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
  2x -8:52 core:backspace (atom-text-editor.editor.is-focused)
     -8:41.7.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -7:18.8.0 core:undo (atom-text-editor.editor.is-focused)
     -7:17.3.0 core:save (atom-text-editor.editor.is-focused)
     -5:16.5.0 titanium:openView (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:08.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:08.4.0 editor:newline (atom-text-editor.editor.is-focused)
  6x -0:05.3.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "related-split-view",
      "terminal-plus"
    ],
    "themes": [
      "one-dark-ui",
      "oceanic-next"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-backbone, v0.6.1
atom-beautify, vundefined
atom-pair, v2.0.10
atom-ternjs, v0.13.2
autocomplete-modules, v1.4.1
autocomplete-paths, v1.0.2
build, v0.57.0
emmet, v2.4.2
highlight-selected, v0.11.2
hyperclick, v0.0.35
javascript-snippets, v1.2.1
linter, v1.11.3
linter-jshint, v2.0.3
linter-jsonlint, v1.2.1
livereload, v0.4.4
minimap, v4.21.0
oceanic-next, v0.1.2
project-manager, v2.7.6
release-notes, v0.53.0
sync-settings, v0.7.2
titanium-alloy, v0.9.0
titanium-build, v0.8.1

# Dev
No dev packages
```

**Comment by yomybaby** [comment]
Thanks for reporting!
