### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by DouglasHennrich** [yomybaby/atom-titanium#33]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [titanium-alloy](https://github.com/yomybaby/atom-titanium) package, v0.9.11

### Stack Trace

Uncaught TypeError: Path must be a string. Received null

```
At /Users/Odin/.atom/packages/titanium-alloy/lib/ti-pkg-util.js:6

TypeError: Path must be a string. Received null
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:479:5)
    at Object.getAlloyRootPath (/Users/Odin/.atom/packages/titanium-alloy/lib/ti-pkg-util.js:58:17)
    at Object.alloyCompletionRules.getCompletions (/Users/Odin/.atom/packages/titanium-alloy/lib/controllerProvider.coffee:24:28)
    at Object.module.exports.getSuggestions (/Users/Odin/.atom/packages/titanium-alloy/lib/controllerProvider.coffee:138:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:310:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:289:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:276:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -0:57.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:57.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:43.2.0 emmet:toggle-comment (atom-text-editor.editor.is-focused)
     -0:43.2.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -0:38.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:38.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:38.2.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:36.8.0 core:undo (atom-text-editor.editor.is-focused)
  3x -0:36 core:backspace (atom-text-editor.editor.is-focused)
     -0:34.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:34.8.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:33.2.0 core:undo (atom-text-editor.editor.is-focused)
  5x -0:29.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:25.1.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:24.4.0 core:move-up (atom-text-editor.editor.is-focused.autocomplete-active)
  9x -0:21.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-atom-api"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "titanium-alloy": {
    "isAlloy1_8later": false
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.3.3
atom-material-ui, v1.2.10
color-picker, v2.1.1
emmet, v2.4.3
file-icons, v1.7.7
highlight-selected, v0.11.2
hyperclick, v0.0.36
jshint, v1.8.5
jsonlint, v1.1.2
language-javascript-jsx, v0.3.7
pigments, v0.26.0
pretty-json, v1.0.3
titanium-alloy, v0.9.11

# Dev
No dev packages
```

**Comment by yomybaby** [comment]
Thanks for reporting. Can you descibe when you got this error?

**Comment by DouglasHennrich** [comment]
I getting this error when I was on `Snippets` window from Atom... I was just typing snippets and keep getting this error

Thanks =)

**Comment by jasonkneen** [comment]
Any fix for this? or workaround -- keep getting errors popping up

**Comment by yomybaby** [comment]
Did you open a file individually or open a root folder of project?

**Comment by jasonkneen** [comment]
I open atom from the project folder so "atom ."

**Comment by yomybaby** [comment]
Thanks for letting me know.

I need need more detail.

For example :
When did you get this error?
Which file and what key was pressed?
...

2016년 4월 29일 (금) 오전 2:56, Jason Kneen <notifications@github.com>님이 작성:

**Comment by yomybaby** [comment]
v0.9.12 version available. Update and try. Please let me know it work properly. 😄

**Comment by NLKok** [comment]
For me it works, I don't get the error anymore.

**Comment by jasonkneen** [comment]
me too -- looks good

**Comment by yomybaby** [comment]
@NLKok @jasonkneen Great news! 😄

**Comment by DouglasHennrich** [comment]
Yea the bug are fixed but now something else came up... when I use the hot-keys to open `Controllers`, `Views`, `Styles`, it lead me to `projectDic/app/controllers/(controllers, views, styles)` it's add `/controllers` after `/app`

**Comment by yomybaby** [comment]
Sorry for bothering. There is a mistake. I'll fix in a few days.

**Comment by DouglasHennrich** [comment]
Don't need to apologize, you're doing an awesome work!
