### ISSUE TITLE
Uncaught Error: /Users/fokkezb/dev/projects/ComeEmpty.Me/app/controllers does not exist.

### ISSUE THREAD

**Issue by FokkeZB** [yomybaby/atom-titanium#40]
Hi @yomybaby, no idea who this started but I get it all the time now :(

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [titanium-alloy](https://github.com/yomybaby/atom-titanium) package, v0.10.1

### Stack Trace

Uncaught Error: /Users/fokkezb/dev/projects/ComeEmpty.Me/app/controllers does not exist.

```
At /Users/fokkezb/.atom/packages/titanium-alloy/node_modules/find/index.js:194

Error: /Users/fokkezb/dev/projects/ComeEmpty.Me/app/controllers does not exist.
    at Object.error.notExist (/Users/fokkezb/.atom/packages/titanium-alloy/node_modules/find/index.js:68:12)
    at traverseSync (/Users/fokkezb/.atom/packages/titanium-alloy/node_modules/find/index.js:194:38)
    at Object.find.(anonymous function) [as fileSync] (/Users/fokkezb/.atom/packages/titanium-alloy/node_modules/find/index.js:336:5)
    at Object.alloyCompletionRules.getCompletions (/Users/fokkezb/.atom/packages/titanium-alloy/lib/controllerProvider.coffee:28:22)
    at Object.module.exports.getSuggestions (/Users/fokkezb/.atom/packages/titanium-alloy/lib/controllerProvider.coffee:138:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:310:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:289:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:276:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -0:32.7.0 core:paste (atom-text-editor.editor.is-focused)
  3x -0:29.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:25.6.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  3x -0:25.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:20.1.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:19.9.0 core:copy (atom-text-editor.editor.is-focused)
     -0:16.7.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:16.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:15.4.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -0:13.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -0:13.2.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -0:12.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:06.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:05.6.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  3x -0:01.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:01.2.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-ternjs"
    ]
  },
  "titanium-alloy": {
    "numberOfSplitPane": 3
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.7
docblockr, v0.7.3
hyperclick, v0.0.36
linter, v1.11.4
linter-jshint, v2.1.0
titanium-alloy, v0.10.1

# Dev
No dev packages
```

**Comment by FokkeZB** [comment]
👍🤖
