### ISSUE TITLE
Uncaught TypeError: Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by dalinet** [yomybaby/atom-titanium#47]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [titanium-alloy](https://github.com/yomybaby/atom-titanium) package, v0.11.3

### Stack Trace

Uncaught TypeError: Cannot read property 'properties' of undefined

```
At /Users/luisperezgil/.atom/packages/titanium-alloy/lib/controllerProvider.coffee:133

TypeError: Cannot read property 'properties' of undefined
    at /Users/luisperezgil/.atom/packages/titanium-alloy/lib/controllerProvider.coffee:133:51
    at Function._.each._.forEach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jasmine-tagged/node_modules/jasmine-focused/node_modules/jasmine-node/node_modules/underscore/underscore.js:153:9)
    at Object.alloyCompletionRules.getCompletions (/Users/luisperezgil/.atom/packages/titanium-alloy/lib/controllerProvider.coffee:129:11)
    at Object.module.exports.getSuggestions (/Users/luisperezgil/.atom/packages/titanium-alloy/lib/controllerProvider.coffee:204:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:310:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:289:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:276:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
  4x -0:43.4.0 core:close (atom-text-editor.editor.is-focused)
     -0:08.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:04.1.0 core:copy (atom-text-editor.editor.is-focused)
     -0:03.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:02.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:01.9.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.8.3
atom-icons, v0.2.2
atom-material-ui, v1.2.13
build, v0.64.0
busy, v0.5.0
highlight-selected, v0.11.2
hyperclick, v0.0.36
pretty-json, v1.4.1
titanium-alloy, v0.11.3
titanium-build, v0.8.1

# Dev
No dev packages
```

**Comment by yomybaby** [comment]
Thanks for reporting.
