### ISSUE TITLE
Uncaught TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by Mojo-Tribe** [yomybaby/atom-titanium#71]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.3
**Thrown From**: [titanium-alloy](https://github.com/yomybaby/atom-titanium) package 0.14.4

### Stack Trace

Uncaught TypeError: Cannot read property 'bind' of undefined

```
At /Users/mojotribe/.atom/packages/titanium-alloy/lib/controllerProvider.js:412

TypeError: Cannot read property 'bind' of undefined
    at Object.onDidInsertSuggestion (/packages/titanium-alloy/lib/controllerProvider.js:412:85)
    at AutocompleteManager.confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:594:37)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:258:22
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at SuggestionList.confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list.js:145:33)
    at SuggestionListElement.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:234:31)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at SuggestionList.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list.js:150:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  5x -1:45.6.0 core:backspace (input.hidden-input)
     -1:26.5.0 core:copy (input.hidden-input)
     -1:24.9.0 core:paste (input.hidden-input)
     -1:22.7.0 core:backspace (input.hidden-input)
     -1:09.0 core:paste (input.hidden-input)
     -0:58.1.0 core:copy (input.hidden-input)
     -0:56.6.0 core:paste (input.hidden-input)
  5x -0:52 core:backspace (input.hidden-input)
     -0:50.1.0 autocomplete-plus:confirm (input.hidden-input)
     -0:27.1.0 editor:newline (input.hidden-input)
     -0:19.2.0 autocomplete-plus:confirm (input.hidden-input)
  2x -0:17.7.0 core:backspace (input.hidden-input)
     -0:15.4.0 autocomplete-plus:confirm (input.hidden-input)
  7x -0:12.7.0 core:backspace (input.hidden-input)
  2x -0:09.8.0 autocomplete-plus:confirm (input.hidden-input)
     -0:05.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
build 0.68.0 
busy 0.7.0 
hyperclick 0.1.1 
language-diff 0.7.0 
merge-conflicts 1.4.5 
ti-create 0.30.0 
titanium-alloy 0.14.4 
titanium-build 0.8.1 
titanium-language-javascript 0.48.0 
```

**Comment by vsantana** [comment]
There are some clue about it?
